// Product seed data from frontend mockData (shortened version, add more as needed)
export const productSeeds = [
    {
        id: 1,
        name: 'Canon EOS R5',
        categoryId: 2,
        subcategoryId: 21,
        price: 45000000,
        salePrice: 39900000,
        discount: 11,
        rating: 4.8,
        reviews: 245,
        image:
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        images: [
            'https://images-na.ssl-images-amazon.com/images/I/71iKNJ6rVIL.jpg',
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        ],
        description:
            'Canon EOS R5 là chiếc máy ảnh mirrorless full-frame được trang bị các công nghệ tiên tiến nhất của Canon',
        packageContents: [
            'Canon EOS R50 Mirrorless Camera (Black)',
            'Canon LP-E17 Lithium-Ion Battery Pack',
            'Canon LC-E17 Charger for LP-E17 Battery Pack',
        ],
        descriptionSections: [
            {
                title: 'Canon EOS R5 - Chiếc máy ảnh mirrorless full-frame chính hãng của Canon',
                content:
                    'Canon EOS R5 là sự kết hợp hoàn hảo giữa công nghệ tiên tiến, thiết kế chuyên nghiệp và hiệu năng vượt trội.',
            },
        ],
        specifications: {
            sensor: 'Full Frame CMOS 45MP',
            iso: '100 - 51200',
            shutter: '1/8000s',
            videoResolution: '8K 60fps',
            batteryLife: '320 ảnh',
            weight: '738g',
            dimensions: '138.5 x 97.5 x 88.8 mm',
        },
        inStock: true,
        quantity: 50,
        isFeatured: true,
        isFlashSale: true,
    },
    {
        id: 2,
        name: 'Sony A7R V',
        categoryId: 2,
        price: 42000000,
        salePrice: 39900000,
        discount: 5,
        rating: 4.9,
        reviews: 189,
        image:
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        images: [
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        ],
        description:
            'Canon EOS R5 là chiếc máy ảnh mirrorless full-frame được trang bị các công nghệ tiên tiến nhất của Canon',
        packageContents: [
            'Canon EOS R50 Mirrorless Camera (Black)',
            'Canon LP-E17 Lithium-Ion Battery Pack',
        ],
        descriptionSections: [],
        specifications: {
            sensor: 'Full Frame CMOS 45MP',
            iso: '100 - 51200',
        },
        inStock: true,
        quantity: 35,
        isFeatured: true,
        isFlashSale: false,
    },
    {
        id: 3,
        name: 'Nikon Z9',
        categoryId: 2,
        price: 48000000,
        salePrice: 48000000,
        discount: 0,
        rating: 4.7,
        reviews: 156,
        image: 'https://images-na.ssl-images-amazon.com/images/I/71iKNJ6rVIL.jpg',
        images: [
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        ],
        description:
            'Canon EOS R5 là chiếc máy ảnh mirrorless full-frame được trang bị các công nghệ tiên tiến nhất của Canon',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 20,
        isFeatured: true,
        isFlashSale: false,
    },
    {
        id: 4,
        name: 'Canon EOS 5D Mark IV',
        categoryId: 1,
        price: 36000000,
        salePrice: 27900000,
        discount: 23,
        rating: 4.6,
        reviews: 312,
        image: 'https://images-na.ssl-images-amazon.com/images/I/71iKNJ6rVIL.jpg',
        images: [],
        description: 'DSLR Camera professional',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 45,
        isFeatured: false,
        isFlashSale: true,
    },
    {
        id: 5,
        name: 'Nikon D850',
        categoryId: 1,
        price: 32000000,
        salePrice: 32000000,
        discount: 0,
        rating: 4.8,
        reviews: 234,
        image: 'https://images-na.ssl-images-amazon.com/images/I/71iKNJ6rVIL.jpg',
        images: [],
        description: 'DSLR Camera professional',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 30,
        isFeatured: true,
        isFlashSale: false,
    },
    {
        id: 6,
        name: 'Canon PowerShot G7 X',
        categoryId: 3,
        price: 15000000,
        salePrice: 13000000,
        discount: 13,
        rating: 4.4,
        reviews: 89,
        image: 'https://images-na.ssl-images-amazon.com/images/I/71iKNJ6rVIL.jpg',
        images: [],
        description: 'Compact premium camera for travel',
        packageContents: [],
        descriptionSections: [],
        specifications: {
            sensor: '1 inch CMOS 20.1MP',
            iso: '100 - 3200',
        },
        inStock: true,
        quantity: 60,
        isFeatured: false,
        isFlashSale: true,
    },
    {
        id: 7,
        name: 'Sony RX100 VII',
        categoryId: 3,
        price: 20000000,
        salePrice: 18400000,
        discount: 8,
        rating: 4.7,
        reviews: 156,
        image: 'https://images-na.ssl-images-amazon.com/images/I/71iKNJ6rVIL.jpg',
        images: [],
        description: 'Premium compact camera with superior optics',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 40,
        isFeatured: true,
        isFlashSale: false,
    },
    {
        id: 8,
        name: 'Canon EF 24mm f/2.8',
        categoryId: 4,
        price: 12000000,
        salePrice: 12000000,
        discount: 0,
        rating: 4.3,
        reviews: 78,
        image:
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        images: [],
        description: 'Standard EF mount lens',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 100,
        isFeatured: false,
        isFlashSale: false,
    },
    {
        id: 9,
        name: 'Nikon Z 70-200mm f/2.8',
        categoryId: 4,
        price: 28000000,
        salePrice: 28000000,
        discount: 0,
        rating: 4.9,
        reviews: 234,
        image:
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        images: [],
        description: 'Professional telephoto lens',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 25,
        isFeatured: true,
        isFlashSale: false,
    },
    {
        id: 10,
        name: 'Peak Design Capture Clip',
        categoryId: 5,
        price: 10000000,
        salePrice: 10000000,
        discount: 0,
        rating: 4.6,
        reviews: 567,
        image:
            'https://product.hstatic.net/200000409445/product/20_a5fafddf48c6423eab730f4bdee6b252_master.jpg',
        images: [],
        description: 'Quick access camera clip',
        packageContents: [],
        descriptionSections: [],
        specifications: {},
        inStock: true,
        quantity: 200,
        isFeatured: false,
        isFlashSale: false,
    },
];
