// Store seed data from frontend mockData
export const storeSeeds = [
    {
        id: 1,
        name: 'ASTER Production',
        address: '202, Đường Lê Văn Việt, Phường 1, Quận 10, TP.HCM',
        phones: ['0794352262'],
        email: 'asterproduction333@gmail.com',
        hours: '8:00 AM - 9:00 PM',
        latitude: 21.0285,
        longitude: 105.7842,
        featured: true,
        description: 'Cửa hàng chính, phục vụ toàn bộ TP.HCM',
    },
    {
        id: 2,
        name: 'ASTER Production',
        address: '202, Đường Lê Duẩn, Phường 3, Quận 10, TP.HCM',
        phones: ['0794352262'],
        email: 'asterproduction333@gmail.com',
        hours: '8:00 AM - 9:00 PM',
        latitude: 21.0285,
        longitude: 105.7853,
        featured: false,
        description: 'Cửa hàng chính, phục vụ toàn bộ TP.HCM',
    },
    {
        id: 3,
        name: 'ASTER Production',
        address: '202, Đường Nguyễn Đình Chiểu, Phường 3, Quận 3, TP.HCM',
        phones: ['0794352262'],
        email: 'asterproduction333@gmail.com',
        hours: '8:00 AM - 9:00 PM',
        latitude: 21.0285,
        longitude: 105.7853,
        featured: false,
        description: 'Cửa hàng chính, phục vụ toàn bộ TP.HCM',
    },
    {
        id: 4,
        name: 'ASTER Production',
        address: '321 Lê Hồng Phong, Phường 2, Quận 10, Hồ Chí Minh',
        phones: ['0794352262'],
        email: 'asterproduction333@gmail.com',
        hours: '8:00 AM - 9:00 PM',
        latitude: 21.0285,
        longitude: 105.7842,
        featured: false,
        description: 'Cửa hàng chính, phục vụ toàn bộ TP.HCM',
    },
];
